// Authentication
const SIGN_UP_INIT = "SIGN_UP_INIT";
const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
const SIGN_UP_ERROR = "SIGN_UP_ERROR";

const OTP_VERIFY_INIT = "OTP_VERIFY_INIT";
const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS";
const OTP_VERIFY_ERROR = "OTP_VERIFY_ERROR";

const SET_PIN_INIT = "SET_PIN_INIT";
const SET_PIN_SUCCESS = "SET_PIN_SUCCESS";
const SET_PIN_ERROR = "SET_PIN_ERROR";

const LOGIN_USER_INIT = "LOGIN_USER_INIT";
const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

const FORGOT_PIN_INIT = "FORGOT_PIN_INIT";
const FORGOT_PIN_SUCCESS = "FORGOT_PIN_SUCCESS";
const FORGOT_PIN_ERROR = "FORGOT_PIN_ERROR";

const RESET_PIN_INIT = "RESET_PIN_INIT";
const RESET_PIN_SUCCESS = "RESET_PIN_SUCCESS";
const RESET_PIN_ERROR = "RESET_PIN_ERROR";

// Ask Query
const CONTACT_US_INIT = "CONTACT_US_INIT";
const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
const CONTACT_US_ERROR = "CONTACT_US_ERROR";

const SUBSCRIBE_NEWSLATER_INIT = "SUBSCRIBE_NEWSLATER_INIT";
const SUBSCRIBE_NEWSLATER_SUCCESS = "SUBSCRIBE_NEWSLATER_SUCCESS";
const SUBSCRIBE_NEWSLATER_ERROR = "SUBSCRIBE_NEWSLATER_ERROR";

// Legal Help
const GET_LEGAL_HELP_INIT = "GET_LEGAL_HELP_INIT";
const GET_LEGAL_HELP_SUCCESS = "GET_LEGAL_HELP_SUCCESS";
const GET_LEGAL_HELP_ERROR = "GET_LEGAL_HELP_ERROR";

// Give Help
const GIVE_HELP_INIT = "GIVE_HELP_INIT";
const GIVE_HELP_SUCCESS = "GIVE_HELP_SUCCESS";
const GIVE_HELP_ERROR = "GIVE_HELP_ERROR";

// Emergency Help
const EMERGENCY_HELP_INIT = "EMERGENCY_HELP_INIT";
const EMERGENCY_HELP_SUCCESS = "EMERGENCY_HELP_SUCCESS";
const EMERGENCY_HELP_ERROR = "EMERGENCY_HELP_ERROR";

// Payment Help
const PAYMENT_INIT = "PAYMENT_INIT";
const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
const PAYMENT_ERROR = "PAYMENT_ERROR";

export {
    // Authentication
    SIGN_UP_INIT,
    SIGN_UP_SUCCESS,
    SIGN_UP_ERROR,

    OTP_VERIFY_INIT,
    OTP_VERIFY_SUCCESS,
    OTP_VERIFY_ERROR,

    SET_PIN_INIT,
    SET_PIN_SUCCESS,
    SET_PIN_ERROR,

    LOGIN_USER_INIT,
    LOGIN_USER_SUCCESS,
    LOGIN_USER_ERROR,

    FORGOT_PIN_INIT,
    FORGOT_PIN_SUCCESS,
    FORGOT_PIN_ERROR,

    RESET_PIN_INIT,
    RESET_PIN_SUCCESS,
    RESET_PIN_ERROR,

    // Ask Query
    CONTACT_US_INIT,
    CONTACT_US_SUCCESS,
    CONTACT_US_ERROR,

    SUBSCRIBE_NEWSLATER_INIT,
    SUBSCRIBE_NEWSLATER_SUCCESS,
    SUBSCRIBE_NEWSLATER_ERROR,

    // Legal Help
    GET_LEGAL_HELP_INIT,
    GET_LEGAL_HELP_SUCCESS,
    GET_LEGAL_HELP_ERROR,

    // Give Help
    GIVE_HELP_INIT,
    GIVE_HELP_SUCCESS,
    GIVE_HELP_ERROR,

    // Emergency Help
    EMERGENCY_HELP_INIT,
    EMERGENCY_HELP_SUCCESS,
    EMERGENCY_HELP_ERROR,

    // Payment Help
    PAYMENT_INIT,
    PAYMENT_SUCCESS,
    PAYMENT_ERROR
};
